#https://www.youtube.com/watch?v=W_Fhjmsq7hU

name: Hello GitHub Actions
 
on:
    push:
        branches: ["*"]

jobs:
    build:
        runs-on: ubuntu-latest  # Máquina em que está rodando
       # Linux *1 Windows *2 Mac *10 Multiplicadores 2 mil minutos é mais comun rodar em linux
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: npm ci
            - run: npm run test
            - run: npm run build
            - run: npm run deploy


